### ISSUE TITLE
Loss of Fees as Low

### ISSUE THREAD

**Issue by indijanc** [code-423n4/org#101]
I'd like to flag a Judging Decision in an effort to uphold and improve C4 reports and profesionalism.
https://github.com/code-423n4/2023-04-caviar-findings/issues/217

The finding was judged as Low with the following comments:

> Fees will round down to zero due to integer math, I believe this is Low Severity
The fact that this can be done by the owner further reduces impact, but I believe it's still QA - Low

> Thank you for the feedback @indijanc I still believe that a rounding error is Low Severity as the loss is marginal, I think quality was good and believe if you sent more this would have been awarded as QA

> Also note that inputAmount is normalized in 1e18s meaning that this should not happen unless it's misconfigured

The concerning part here is that it seems the root cause of the finding was used for categorization of the issue. I believe the IT industry is pretty much aligned on how a security issue categorization or severity is determined. There's slight differences here and there but they're all based on impact and likelihood. Here's what I believe is a good reference and description for issue categorization (rating) - [OWASP Risk Rating Methodology](https://owasp.org/www-community/OWASP_Risk_Rating_Methodology)

C4 documentation has this [nicely condensed](https://docs.code4rena.com/awarding/judging-criteria/severity-categorization) in the following guidelines:
> QA (Quality Assurance) Includes both Non-critical (code style, clarity, syntax, versioning, off-chain monitoring (events, etc) and Low risk (e.g. assets are not at risk: state handling, function incorrect as to spec, issues with comments). Excludes Gas optimizations, which are submitted and judged separately.
2 — Med: Assets not at direct risk, but the function of the protocol or its availability could be impacted, or leak value with a hypothetical attack path with stated assumptions, but external requirements.
3 — High: Assets can be stolen/lost/compromised directly (or indirectly if there is a valid attack path that does not have hand-wavy hypotheticals).

So based on the fact that the finding describes how a Pool owner can avoid the Protocol Fees, it falls pretty well under the "leak value" part of a Medium categorization. So when the reasoning for a Low categorization was based on the root cause (rounding on division in this case) I though to myself "Ugh, would then draining of all funds because of integer math be considered as medium? As impact is High but root cause is Low ..."

The last comment for reasoning about the issue categorization indicates that likelihood was indeed considered but again misassessed. The inputAmount (based on virtualNftReserves) is not normalized to 1e18 anywhere in the files of the audit scope, and is only recommended - sponsor acknowledged this with several comments in public chat during the contest. And discarding the likelihood with the famous words "this should not happen" is almost ironic :). Misconfigurations I would argue are one of the first and easiest attack vectors that malicious users and bad actors will abuse.

Disclaimer: I submitted the mentioned finding, so of course I am totally biased. But even putting my unbiased hat on (if that's even possible :) ) I don't think this was properly assesed and was miscategorized by looking at root cause instead of understanding the context and assessing impact and likelihood. How would other judges mark this? Do you also consider root cause when deciding on the severity of a finding? @trust1995 @dmvt @0xean @0xleastwood @horsefacts @berndartmueller @Picodes @kirk-baird @Simon-Busch @hansfriese @GalloDaSballo 

Please note that I otherwise have great respect for the judge in this contest as he's an awesome contributor to the community and transparent in all his actions, but I feel there's always room for improvement. Judging these contests with huge amount of findings I know is hard work and just drains you, and you simply cannot make correct decisions every time, but I hope we're not sacrifising quality and profesionalism to gain speed.

**Comment by KnownFactC4** [comment]
Per the Autumn 2023 C4 Supreme Court verdicts, the Supreme Court's verdict on this issue is: 

> Loss of fees should be regarded as an impact similar to any other loss of capital:
> Loss of dust amounts are QA
> Loss of real amounts depends on specific conditions and likelihood considerations


Link to verdict: https://docs.google.com/document/d/1Y2wJVt0d2URv8Pptmo7JqNd0DuPk_qF9EPJAj3iSQiE/edit#heading=h.za6btcxjvn88
