### ISSUE TITLE
Can't log in my code4rena account.

### ISSUE THREAD

**Issue by Parth-Sharma-tonchi** [code-423n4/org#151]
For the past 4 days, I have not been able to log in to my code4rena account. I can't submit my audit findings because of this. It is kept on the following page: 
[Code4rena _ Keeping high severity bugs out of production.pdf](https://github.com/code-423n4/org/files/14602456/Code4rena._.Keeping.high.severity.bugs.out.of.production.pdf)  

And it also gives this error sometimes : ```Oops...something went wrong: XMLHttpRequest failed: "Unable to connect to the Parse API"```

Please Help...

**Comment by trust1995** [comment]
Recommend closing this, not the right place for support desk.
