### ISSUE TITLE
Bias in Judging

### ISSUE THREAD

**Issue by nobodytrue** [code-423n4/org#153]
Let's confront the glaring issue head-on. Recent contests have revealed a troubling pattern: having a reputation confers an unfair advantage. It appears that every issue from someone with a reputation receives a 'sufficient-quality' stamp from the pre-sorter, or the Judge approves blatantly invalid submissions from individuals with a reputation while disregarding all other escalations. This trend must be addressed, and one potential solution is to introduce participant anonymization to promote fairness and equity across the board.

**Comment by bytes032** [comment]
The issue is that once PJQA starts, you know who's who.

There's no easy way to solve that. What are your thoughts on this?
