### ISSUE TITLE
Severity standardization - Centralization risks

### ISSUE THREAD

**Issue by trust1995** [code-423n4/org#54]
It would be beneficial for all of us to standardize severities for common issues, as we have seen variance among judges and contests.

Example of two different severities:
[Frax Liquidity contest](https://github.com/code-423n4/2022-09-frax-findings/issues/107) - Admin can freely set important parameters and add minters. Judged as M
[Rubicon contest](https://github.com/code-423n4/2022-05-rubicon-findings/issues/344) -  admin can change important parameters - downgraded to QA.

We need to have a fixed policy on how to judge centralization risks.
One simple option is - max severity for any privileged function abuse is Low
The other extreme - lack of timelocked admin contract for any meaningful change to the protocol could be Medium risk
Obviously there are various middle of the road approached.

Personally I think that centralization risks CAN be considered M findings, provided the report shows a unique attack path which users were not told upfront about. For example in [VTVL](https://github.com/code-423n4/2022-09-vtvl-findings/issues/475), admin can revoke user's staked tokens, after the staking period. Since this is not something users would see in advance, and it impacts their assets by right, so it does warrant a major severity level.

Opinions are welcome.
@GalloDaSballo

**Comment by GalloDaSballo** [comment]
Wrote proper discussion piece here:
https://github.com/code-423n4/org/issues/59

Please forward the discussion here and let's build a set of rules and principles around Admin Privilege

**Comment by kartoonjoy** [comment]
Per the Autumn 2023 C4 Supreme Court verdicts, the Supreme Court's verdict on this issue is:

> Submissions would be separated into subcategories:
> - Direct misuse of privileges shall be submitted in the Analysis report
> - Reckless admin mistakes are invalid. Assume calls are previewed.
> - Mistakes in code only unblocked through admin mistakes are QA-level
> - Privilege escalation issues are judged by likelihood and impact and their severity is uncapped.
