### ISSUE TITLE
Proposition for collection and processing of judge performance

### ISSUE THREAD

**Issue by trust1995** [code-423n4/org#71]
C4 accumulated a healthy count of judges in its lineup. Alongside the positives that come from diversity, we are increasingly susceptible to a gap in quality between different judges. While most judges are excellent (Attempt to fully understand raised issues, open to feedback, nuanced, make a best-effort to finish judging quickly), there are some that lack in one department or another.

I believe the lack of feedback on judge performance is detrimental to the self-improvement of the judge and the organization and ultimately to warden motivation, which is a tremendous resource in the C4 force.

For these reasons, I propose a per-contest feedback collection mechanism, from both wardens and sponsors. Feedback will ideally include a score on:
1. Judging completion time
2. Balance and nuance of judging, ability to relate to raised issues in-depth.
3. Neutrality of judging (have two almost identical reports been rated differently?)
4. Qualitative analysis of post-judging QA (was judge responsive to feedback, were there too many errors in the initial judging?)

Obviously, it is not the intention that wardens "penalize" judges who did not accept their submissions, all feedback needs to be well constructed and objective in order to count.

Would love to hear your thoughts on this proposal, which I believe will help increase transparency and accountability in a crucial part of the C4 pipeline.

**Comment by csanuragjain** [comment]
I think point number 1 could be removed from feedback for now since it depends from project to project. Saying this because:

1. Some project have too many reports (Not talking about projects which have lots of duplicates of low hanging which could be done faster, but for a project where duplicates are very less and reports are higher then it becomes difficult to judge)
2. Project/Submitted Report is super complex and judge need to refer to multiple documentation in order to understand (we are all learning). 
3. Lots of wardens query

Although I think remaining points are important and feedback on these will help c4 grow better :)

Judges as always are doing awesome job but due to high volume of reports sometime misses things. Feedback on these should help both judges and wardens in long run

**Comment by Shungy** [comment]
@csanuragjain Also, the judging time is objective, it needs not explicit feedback.

@trust1995 Do you intend the feedbacks/ratings to be public or sent privately to the judge? I think making it private would prevent petty wardens to try harm the credibility of a judge. So it would just be for judge's own use to improve themselves.

**Comment by trust1995** [comment]
@Shungy 
I believe in full transparency of this process. Make everything public for others to see and make their own opinions.

Agree that judging time doesn't necessarily need to be in the feedback report, but it does need to be something judges are measured on (total issues / days taken ratio) .

**Comment by 0xA5DF** [comment]
While I agree there's a need to feedback for judges' work, I also think this might become a source of unnecessary drama from wardens who are unhappy with a totally reasonable and just verdict.

Maybe adding an option to rate without comment can reduce the drama.
I think that a rating system tends to attract more positive feedback (i.e. people that are happy will be more likely to send feedback if it doesn't require them to add any comment) and you can easily see the avg score and ignore the noisy drama in case of a good judge

**Comment by dmvt** [comment]
I really like the idea of having judge feedback/scoring. I think it will increase the overall quality and consistency of the judging effort. 

I do think we should stabilize the scoring mechanism for contests before this happens, however. Right now, the whole ecosystem is adjusting differently to the changes made in the last three months. My concern with starting this before that adjustment period is over and the full penalty cycle is implemented is that upset with the current in-flux state of things may bleed into the judges' scores, disproportionately impacting judges (full disclaimer: like myself) who are highly active during this transition period. The other possibility would be to start with C4 staff rating the judges and introduce warden ratings once the kinks are worked out.

On the specific points proposed:

1) this is already part of the proposed payment mechanism for presort
2) great idea, but highly subjective, so some form of guidelines would have to be developed around this
3) there should probably be a time limit on this - specifically sometimes the judging community decides on a common rule and that results in issues being judged differently before and after the rule is agreed
4) great idea

**Comment by kartoonjoy** [comment]
During the Autumn 2023 C4 Supreme Court session, the Supreme Court issued a set of advisory recommendations, which can be viewed here: 
https://docs.google.com/document/d/1Y2wJVt0d2URv8Pptmo7JqNd0DuPk_qF9EPJAj3iSQiE/edit#heading=h.ubmk8osrs1bw
