### ISSUE TITLE
Adding 75% credit as an option

### ISSUE THREAD

**Issue by dmvt** [code-423n4/org#76]
Right now we (judges) can choose to give 25%, 50%, or 100% credit to an issue. I'd like to see a 75% option added. There have been multiple issues in the last few contests where 100% feels like too much, but 50% feels too harsh.

**Comment by JeffCX** [comment]
shall we please implement the 75% label as requested by the judge @dmvt

**Comment by KnownFactC4** [comment]
During the Autumn 2023 C4 Supreme Court session, the Supreme Court issued a set of advisory recommendations, which can be viewed here: https://docs.google.com/document/d/1Y2wJVt0d2URv8Pptmo7JqNd0DuPk_qF9EPJAj3iSQiE/edit#heading=h.pdjxdbrau0ls
