### ISSUE TITLE
Severity standardization - Protocol does not support CryptoPunks

### ISSUE THREAD

**Issue by trust1995** [code-423n4/org#77]
Cryptopunks do not conform to ERC721. Since the majority of NFT-centric protocols use the ERC721 interface to interact with NFTs, they do not support CryptoPunks without some additional wrapping. It is a very common report to see in NFT related contests, and has in the past mostly been judged as QA:

[Nibble](https://github.com/code-423n4/2022-06-nibbl-findings/issues/302) - QA
[Blur](https://github.com/code-423n4/2022-10-blur-findings/issues/443) - QA
[PartyDAO](https://github.com/code-423n4/2022-09-party-findings/issues/248) - QA
[Cally](https://github.com/code-423n4/2022-05-cally-findings/issues/207) - QA
[Foundation](https://github.com/code-423n4/2022-02-foundation-findings/issues/74) - MED

Note that in the Nibble discussion, the judge which was the Foundation sponsor remarked that it was too generous to Ack as MED.

It seems like, by our severity guidelines, the issue is QA level. Punks can be wrapped externally and treated as ERC721. Also it sounds more like a feature request than something that is automatically assumed to be available.

Feel free to post feedback below.

**Comment by dmvt** [comment]
I agree 100% with this. This issue should be QA.

**Comment by GalloDaSballo** [comment]
Low because you can wrap them

**Comment by KnownFactC4** [comment]
Per the Autumn 2023 C4 Supreme Court verdicts, the Supreme Court's verdict on this issue is: 

> QA as Refactoring / Improvement
> Cannot be argued as a vulnerability


Link to verdict: https://docs.google.com/document/d/1Y2wJVt0d2URv8Pptmo7JqNd0DuPk_qF9EPJAj3iSQiE/edit#heading=h.7ut9cawrjeap
